//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSurveyMatrix
    {
        public long SurveyMatrixId { get; set; }
        public Nullable<long> SurveyId { get; set; }
        public Nullable<int> AnsTypeId { get; set; }
        public string OptionText { get; set; }
    
        public virtual tblSurveyAnswerType tblSurveyAnswerType { get; set; }
        public virtual tblSurvey tblSurvey { get; set; }
    }
}
