//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserQuestionAnswer
    {
        public long UserAnsId { get; set; }
        public long UserId { get; set; }
        public long QuizId { get; set; }
        public long QuestionId { get; set; }
        public string SelectedAns { get; set; }
        public bool IsTrueAns { get; set; }
        public System.DateTime AnswerDate { get; set; }
    
        public virtual tblQuestion tblQuestion { get; set; }
        public virtual tblQuiz tblQuiz { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
