//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Verve_AdminEntities : DbContext
    {
        public Verve_AdminEntities()
            : base("name=Verve_AdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBlog> tblBlogs { get; set; }
        public virtual DbSet<tblBlogComment> tblBlogComments { get; set; }
        public virtual DbSet<tblBlogLike> tblBlogLikes { get; set; }
        public virtual DbSet<tblChannel> tblChannels { get; set; }
        public virtual DbSet<tblTopic> tblTopics { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblSurveyMatrix> tblSurveyMatrices { get; set; }
        public virtual DbSet<tblSurveyAnswerType> tblSurveyAnswerTypes { get; set; }
        public virtual DbSet<tblSurvey> tblSurveys { get; set; }
        public virtual DbSet<tblQuiz> tblQuizs { get; set; }
        public virtual DbSet<tblQuestion> tblQuestions { get; set; }
        public virtual DbSet<tblQuestionOptionMapping> tblQuestionOptionMappings { get; set; }
        public virtual DbSet<tblUserQuestionAnswer> tblUserQuestionAnswers { get; set; }
    
        public virtual int GetCommentByMultipleBlog(string strComment)
        {
            var strCommentParameter = strComment != null ?
                new ObjectParameter("strComment", strComment) :
                new ObjectParameter("strComment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetCommentByMultipleBlog", strCommentParameter);
        }
    
        public virtual int GetLikeByMultipleBlog(string strLike)
        {
            var strLikeParameter = strLike != null ?
                new ObjectParameter("strLike", strLike) :
                new ObjectParameter("strLike", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetLikeByMultipleBlog", strLikeParameter);
        }
    }
}
